### ISSUE TITLE
/scripts/libs/jquery.js:2 發生了卡死現象

### ISSUE THREAD

**Issue by ghost** [Losses/Masochist-board#13]
### /etc/nginx/nginx.conf

user nobody;
worker_processes 8;
error_log /var/log/nginx_error.log info;

events {
    use epoll;
    worker_connections 1024;
}

http {
    server {
        server_name m-b.science;
        listen 443;
        root /home/nanafa/Masochist-board;
        index index.html index.htm index.php;

```
    location / {
        if (-f /srv/nginx/maintenance.html) {
            return 503;
        }
    }

    location ~* \.(ico|css|js|gif|jpe?g|png|bmp|swf)$ {
        expires 1d;
    }
    location ~ \.php(\/.*)*$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
# NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini

# With php5-fpm:
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    error_page 503 @maintenance;
    location @maintenance {
        root /srv/nginx;
        rewrite ^(.*)$ /maintenance.html break;
    }
}

server {
    server_name m-b.science;
    listen 80;
    root /home/nanafa/Masochist-board;
    index index.html index.htm index.php;

    location / {
        if (-f $document_root/maintenance.html) {
            return 503;
        }

        if (-f $request_filename/index.html){
            rewrite (.*) $1/index.html break;
        }
        if (-f $request_filename/index.php){
            rewrite (.*) $1/index.php;
        }
        if (!-f $request_filename){
            rewrite (.*) /index.php;
        }
    }

    location ~* \.(ico|css|js|gif|jpe?g|png|bmp|swf)$ {
        expires 1d;
    }

    error_page 503 @maintenance;
    location @maintenance {
        rewrite ^(.*)$ /maintenance.html break;
    }
}
```

}

按照上面那樣配置，在打開 127.0.0.1 的時候，jquery.js 卡死了。
不知道是配置錯誤還是項目本身的問題。

**Comment by Losses** [comment]
我认为是配置的问题……

**Comment by ghost** [comment]
我沒辦法去自己研究如何配置項目。請在 wiki 裏面新建條目好指導一下吧。

**Comment by Losses** [comment]
抱歉我最近在忙挑战杯的事情把这边耽搁了…… js卡死请手工输入js文件地址检查返回内容

**Comment by ghost** [comment]
返回 500 Internal Server Error .

Log:
2015/05/29 20:32:08 [error] 32121#0: *7 open() "/home/nanafa/Masochist-board/v.gif" failed (2: No such file or directory), client: 127.0.0.1, server: m-b.science, request: "GET /v.gif?pid=307&type=3071&sc=1354,3161,1366,741&desturl=http%3A%2F%2Fwww.xiami.com%2Fsong%2F1770192256%3Fspm%3Da1z1s.6843761.226669510.9.JGs3gm%26from%3Dsearch_popup_song&apitype=1&linkid=ia9labushzf&velo_load=224&velo_cssload=118&velo_jsLoad=113&cite_uid=0&cite_type=1&cite_mini=0 HTTP/1.1", host: "nsclick.baidu.com", referrer: "http://www.xiami.com/artist/89527?spm=a1z1s.3061781.6856533.10.nlJ9fE"

**Comment by Losses** [comment]
请检查你的浏览器插件……怎么会有百度出现……

**Comment by ghost** [comment]
VimFx, FoxyProxy, UserAgent 修改插件。

**Comment by Losses** [comment]
全部禁用 再试

**Comment by ghost** [comment]
我現在沒有心思再繼續研究下去了。
順便說一句，我寫的客戶端也同時停止開發了。
